### ISSUE TITLE
Error when restarting Scriptform

### ISSUE THREAD

**Issue by fboender** [fboender/scriptform#1]
When executing:

    # /etc/init.d/scriptform restart

An error message appears in the log file:

    2017-01-04 14:03:35,804:MAIN:ERROR:_cleanup() takes at most 2 arguments (3 given)
    Traceback (most recent call last):
      File "/usr/bin/scriptform", line 234, in main
        scriptform_instance.run(listen_port=options.port)
      File "/usr/bin/scriptform", line 144, in run
        self.httpd.serve_forever()
      File "/usr/lib/python2.7/SocketServer.py", line 231, in serve_forever
        poll_interval)
      File "/usr/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
        return func(*args)
    TypeError: _cleanup() takes at most 2 arguments (3 given)

**Comment by fboender** [comment]
Fixed. Unlike C, python sends a second argument with the stack frame to the signal handler callback.
